### ISSUE TITLE
Add name field to World typeclass?

### ISSUE THREAD

**Issue by wmbuchanan** [meghanahickey/CTLBranchingFutures#1]
Should we add a name field to the World typeclass in World.hs? We either need to do that, or make sure no two worlds have the exact same proposition set. Otherwise the program thinks they're the same world and throws everything out of whack.

**Comment by meghanahickey** [comment]
Yeah, we definitely should. that'll make debugging easier as well.

**Comment by wmbuchanan** [comment]
Done
